import type { Design } from "@/lib/types";

/**
 * Phase-1 fake data for the /desk shell. Deliberately covers every state the
 * UI must handle: clean pass, hard fails, warnings, generating, live, killed.
 * Replaced by real DB reads in phase 5.
 */

const svgPlaceholder = (label: string, bg: string, fg: string) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000">
      <rect width="800" height="1000" fill="${bg}"/>
      <text x="400" y="470" font-family="Georgia, serif" font-size="52" fill="${fg}" text-anchor="middle">${label}</text>
      <text x="400" y="540" font-family="Georgia, serif" font-size="24" fill="${fg}" opacity="0.6" text-anchor="middle">artwork proof</text>
    </svg>`
  )}`;

export const SEED_DESIGNS: Design[] = [
  {
    id: "a1b2c3d4-0001-4000-8000-000000000001",
    slug: "consider-the-lilies",
    concept: "Consider the lilies — botanical line engraving, three lilies, arched text",
    prompt:
      'Vintage botanical engraving of three lilies, arched text "Consider the lilies of the field, how they grow" above, "MATTHEW 6:28" below, artwork plate only, no garment and no mockup, no gradients, no drop shadows, no photographic texture, hard flat shapes, crisp edges, ready for 3 screen separations',
    model: "recraft_v4_1",
    verseRef: "Matthew 6:28",
    translation: "KJV",
    verseText:
      "And why take ye thought for raiment? Consider the lilies of the field, how they grow; they toil not, neither do they spin:",
    artworkUrl: svgPlaceholder("Consider the lilies", "#EDE7DA", "#141210"),
    artworkFormat: "svg",
    widthPx: 4500,
    heightPx: 5400,
    dpi: 300,
    colorCount: 3,
    flatMockupUrl: svgPlaceholder("Flat mockup", "#f5f5f4", "#44403c"),
    modelMockupUrls: [
      svgPlaceholder("Studio torso", "#d6d3d1", "#292524"),
      svgPlaceholder("Lifestyle", "#a8a29e", "#1c1917"),
    ],
    garmentSku: "gelato-tee-heavy-natural",
    garmentName: "Heavyweight Tee — Natural",
    supplier: "gelato",
    costCents: 1240,
    priceCents: 3400,
    checks: [
      { key: "verse_match", status: "pass", note: "Rendered text exact-matches KJV Matthew 6:28 after normalization." },
      { key: "translation_license", status: "pass", note: "KJV is public domain — on the merchandise allowlist." },
      { key: "resolution", status: "pass", note: "SVG artwork is resolution-independent; auto-pass." },
      { key: "alpha_halo", status: "pass", note: "No partial-transparency fringing on sampled edges." },
      { key: "stroke_weight", status: "pass", note: "Thinnest stroke is 1.6pt at print size (min 1.2pt)." },
      { key: "ink_count", status: "pass", note: "3 distinct colors — within the 4-screen budget." },
      { key: "trademark", status: "pass", note: "No blocklist term found in prompt or rendered text." },
    ],
    status: "ready",
    shopifyProductId: null,
    shopifyHandle: null,
    igMediaId: null,
    createdAt: "2026-07-21T14:12:00Z",
    decidedAt: null,
    publishedAt: null,
    error: null,
  },
  {
    id: "a1b2c3d4-0002-4000-8000-000000000002",
    slug: "be-still-mountains",
    concept: "Be still — minimalist mountain range, NIV text (should be blocked)",
    prompt:
      'Minimalist mountain line art with "Be still, and know that I am God" and "PSALM 46:10" beneath, artwork plate only, no garment and no mockup, no gradients, no drop shadows, no photographic texture, hard flat shapes, crisp edges, ready for 2 screen separations',
    model: "recraft_v4_1",
    verseRef: "Psalm 46:10",
    translation: "NIV",
    verseText:
      "He says, “Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.”",
    artworkUrl: svgPlaceholder("Be still", "#141210", "#EDE7DA"),
    artworkFormat: "png",
    widthPx: 2048,
    heightPx: 2560,
    dpi: 150,
    colorCount: 2,
    flatMockupUrl: svgPlaceholder("Flat mockup", "#292524", "#e7e5e4"),
    modelMockupUrls: [svgPlaceholder("Studio torso", "#1c1917", "#d6d3d1")],
    garmentSku: "gelato-tee-heavy-black",
    garmentName: "Heavyweight Tee — Black",
    supplier: "gelato",
    costCents: 1240,
    priceCents: 3400,
    checks: [
      { key: "verse_match", status: "pass", note: "Rendered text matches the supplied NIV verse text after normalization." },
      { key: "translation_license", status: "fail", note: "NIV is copyrighted (Biblica); its permissions exclude merchandise. Allowed: KJV, ASV, WEB." },
      { key: "resolution", status: "fail", note: "Raster artwork is 2048×2560 at 150 DPI — below the 4500×5400 @ 300 DPI print minimum." },
      { key: "alpha_halo", status: "warn", note: "Partial-transparency fringing detected on 4.2% of sampled edge pixels." },
      { key: "stroke_weight", status: "pass", note: "Thinnest stroke is 2.1pt at print size (min 1.2pt)." },
      { key: "ink_count", status: "pass", note: "2 distinct colors — within the 4-screen budget." },
      { key: "trademark", status: "pass", note: "No blocklist term found in prompt or rendered text." },
    ],
    status: "ready",
    shopifyProductId: null,
    shopifyHandle: null,
    igMediaId: null,
    createdAt: "2026-07-21T16:40:00Z",
    decidedAt: null,
    publishedAt: null,
    error: null,
  },
  {
    id: "a1b2c3d4-0003-4000-8000-000000000003",
    slug: "strength-eagles",
    concept: "Wings as eagles — art-deco eagle, Isaiah 40:31",
    prompt:
      'Art-deco eagle rising, sunburst behind, "they shall mount up with wings as eagles" arched, "ISAIAH 40:31" base, artwork plate only, no garment and no mockup, no gradients, no drop shadows, no photographic texture, hard flat shapes, crisp edges, ready for 4 screen separations',
    model: "recraft_v4_1",
    verseRef: "Isaiah 40:31",
    translation: "WEB",
    verseText:
      "but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.",
    artworkUrl: null,
    artworkFormat: null,
    widthPx: null,
    heightPx: null,
    dpi: null,
    colorCount: null,
    flatMockupUrl: null,
    modelMockupUrls: [],
    garmentSku: "printful-tee-premium-bone",
    garmentName: "Premium Tee — Bone",
    supplier: "printful",
    costCents: 1690,
    priceCents: 4200,
    checks: [],
    status: "generating",
    shopifyProductId: null,
    shopifyHandle: null,
    igMediaId: null,
    createdAt: "2026-07-22T09:05:00Z",
    decidedAt: null,
    publishedAt: null,
    error: null,
  },
  {
    id: "a1b2c3d4-0004-4000-8000-000000000004",
    slug: "amazing-grace-hymnal",
    concept: "Amazing grace — hymnal typography, ornamental border",
    prompt:
      'Victorian hymnal page typography, "Amazing grace! how sweet the sound" ornamental border, artwork plate only, no garment and no mockup, no gradients, no drop shadows, no photographic texture, hard flat shapes, crisp edges, ready for 2 screen separations',
    model: "recraft_v4_1",
    verseRef: null,
    translation: null,
    verseText: null,
    artworkUrl: svgPlaceholder("Amazing grace", "#EDE7DA", "#8A3B24"),
    artworkFormat: "svg",
    widthPx: 4500,
    heightPx: 5400,
    dpi: 300,
    colorCount: 2,
    flatMockupUrl: svgPlaceholder("Flat mockup", "#fafaf9", "#57534e"),
    modelMockupUrls: [
      svgPlaceholder("Studio torso", "#e7e5e4", "#44403c"),
      svgPlaceholder("Lifestyle", "#d6d3d1", "#292524"),
    ],
    garmentSku: "gelato-sweat-crew-bone",
    garmentName: "Crewneck Sweatshirt — Bone",
    supplier: "gelato",
    costCents: 2180,
    priceCents: 5600,
    checks: [
      { key: "verse_match", status: "pass", note: "No verse referenced — check not applicable, auto-pass." },
      { key: "translation_license", status: "pass", note: "No translation referenced — hymn text (1779, public domain)." },
      { key: "resolution", status: "pass", note: "SVG artwork is resolution-independent; auto-pass." },
      { key: "alpha_halo", status: "pass", note: "No partial-transparency fringing on sampled edges." },
      { key: "stroke_weight", status: "warn", note: "Thinnest ornament stroke is 0.9pt at print size — below the 1.2pt minimum, may break up on screen print." },
      { key: "ink_count", status: "pass", note: "2 distinct colors — within the 4-screen budget." },
      { key: "trademark", status: "pass", note: "No blocklist term found in prompt or rendered text." },
    ],
    status: "live",
    shopifyProductId: "gid://shopify/Product/8842911744123",
    shopifyHandle: "amazing-grace-crewneck",
    igMediaId: "17912345678901234",
    createdAt: "2026-07-19T11:30:00Z",
    decidedAt: "2026-07-19T15:02:00Z",
    publishedAt: "2026-07-19T15:04:00Z",
    error: null,
  },
  {
    id: "a1b2c3d4-0005-4000-8000-000000000005",
    slug: "faith-over-fear-neon",
    concept: "Faith over fear — neon script (killed: off-brand)",
    prompt:
      'Neon sign script "faith over fear", artwork plate only, no garment and no mockup, no gradients, no drop shadows, no photographic texture, hard flat shapes, crisp edges, ready for 3 screen separations',
    model: "recraft_v4_1",
    verseRef: null,
    translation: null,
    verseText: null,
    artworkUrl: svgPlaceholder("faith over fear", "#141210", "#B08A31"),
    artworkFormat: "svg",
    widthPx: 4500,
    heightPx: 5400,
    dpi: 300,
    colorCount: 3,
    flatMockupUrl: svgPlaceholder("Flat mockup", "#1c1917", "#d6d3d1"),
    modelMockupUrls: [svgPlaceholder("Studio torso", "#292524", "#a8a29e")],
    garmentSku: "gelato-tee-heavy-black",
    garmentName: "Heavyweight Tee — Black",
    supplier: "gelato",
    costCents: 1240,
    priceCents: 3400,
    checks: [
      { key: "verse_match", status: "pass", note: "No verse referenced — check not applicable, auto-pass." },
      { key: "translation_license", status: "pass", note: "No translation referenced." },
      { key: "resolution", status: "pass", note: "SVG artwork is resolution-independent; auto-pass." },
      { key: "alpha_halo", status: "pass", note: "No partial-transparency fringing on sampled edges." },
      { key: "stroke_weight", status: "pass", note: "Thinnest stroke is 1.4pt at print size (min 1.2pt)." },
      { key: "ink_count", status: "pass", note: "3 distinct colors — within the 4-screen budget." },
      { key: "trademark", status: "pass", note: "No blocklist term found in prompt or rendered text." },
    ],
    status: "killed",
    shopifyProductId: null,
    shopifyHandle: null,
    igMediaId: null,
    createdAt: "2026-07-20T08:15:00Z",
    decidedAt: "2026-07-20T09:00:00Z",
    publishedAt: null,
    error: null,
  },
];

/** Fake IG quota usage for the header meter. Real query lands in phase 7. */
export const SEED_IG_QUOTA = { used: 6, cap: 25 };
